[ERROR] 2017-02-06 18:13:50,345 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-02-06 18:13:50.343881-190.64.49.27-648
[ERROR] 2017-02-06 18:15:58,222 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-02-06 18:15:58.221313-190.64.49.27-c27
